# Generated by Django 4.2.1 on 2023-06-08 19:24

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Poi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120, null=True)),
                ('type', models.CharField(choices=[('University', 'University'), ('Hospital', 'Hospital'), ('Stadium', 'Stadium')], max_length=50)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('area', models.CharField(blank=True, choices=[('Inner London', 'Inner London'), ('Outer London', 'Outer London')], max_length=20, null=True)),
                ('borough', models.CharField(blank=True, max_length=50, null=True)),
                ('listing_type', models.CharField(choices=[('Curricular', 'Curricular'), ('Profissional ', 'Profissional '), ('Voluntário', 'Voluntário')], max_length=20)),
                ('internship_status', models.CharField(blank=True, choices=[('Presencial', 'Presencial'), ('Remoto', 'Remoto'), ('Híbrido', 'Híbrido')], max_length=20, null=True)),
                ('vacancies', models.DecimalField(decimal_places=0, max_digits=2)),
                ('internship_bachelor', models.CharField(blank=True, choices=[('CTeSP', 'CTeSP'), ('Licenciatura', 'Licenciatura'), ('Mestrado', 'Mestrado'), ('Doutoramento', 'Doutoramento')], max_length=20, null=True)),
                ('total_hours', models.IntegerField(blank=True, null=True)),
                ('programming_lang_python', models.BooleanField(default=False)),
                ('programming_lang_java', models.BooleanField(default=False)),
                ('programming_lang_c_1', models.BooleanField(default=False)),
                ('programming_lang_c_2', models.BooleanField(default=False)),
                ('programming_lang_javascript', models.BooleanField(default=False)),
                ('programming_lang_sql', models.BooleanField(default=False)),
                ('programming_lang_php', models.BooleanField(default=False)),
                ('programming_lang_go', models.BooleanField(default=False)),
                ('programming_lang_kotlin', models.BooleanField(default=False)),
                ('programming_lang_matlab', models.BooleanField(default=False)),
                ('programming_lang_swift', models.BooleanField(default=False)),
                ('programming_lang_rust', models.BooleanField(default=False)),
                ('programming_lang_ruby', models.BooleanField(default=False)),
                ('programming_lang_dart', models.BooleanField(default=False)),
                ('programming_lang_scala', models.BooleanField(default=False)),
                ('programming_fw_frontend_angular', models.BooleanField(default=False)),
                ('programming_fw_frontend_jquery', models.BooleanField(default=False)),
                ('programming_fw_frontend_react', models.BooleanField(default=False)),
                ('programming_fw_frontend_ruby', models.BooleanField(default=False)),
                ('programming_fw_frontend_vuejs', models.BooleanField(default=False)),
                ('programming_fw_backend_aspnet', models.BooleanField(default=False)),
                ('programming_fw_backend_django', models.BooleanField(default=False)),
                ('programming_fw_backend_express', models.BooleanField(default=False)),
                ('programming_fw_backend_laravel', models.BooleanField(default=False)),
                ('programming_fw_backend_nodejs', models.BooleanField(default=False)),
                ('programming_fw_backend_spring', models.BooleanField(default=False)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('picture1', models.ImageField(blank=True, null=True, upload_to='pictures/%Y/%m/%d/')),
                ('picture2', models.ImageField(blank=True, null=True, upload_to='pictures/%Y/%m/%d/')),
                ('picture3', models.ImageField(blank=True, null=True, upload_to='pictures/%Y/%m/%d/')),
                ('picture4', models.ImageField(blank=True, null=True, upload_to='pictures/%Y/%m/%d/')),
                ('picture5', models.ImageField(blank=True, null=True, upload_to='pictures/%Y/%m/%d/')),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
