# Generated by Django 4.2.1 on 2023-06-12 14:39

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('area', models.CharField(blank=True, choices=[('Inner London', 'Inner London'), ('Outer London', 'Outer London')], max_length=20, null=True)),
                ('borough', models.CharField(blank=True, max_length=50, null=True)),
                ('listing_type', models.CharField(choices=[('Curricular', 'Curricular'), ('Profissional ', 'Profissional '), ('Voluntário', 'Voluntário')], max_length=20)),
                ('internship_status', models.CharField(blank=True, choices=[('Presencial', 'Presencial'), ('Remoto', 'Remoto'), ('Híbrido', 'Híbrido')], max_length=20, null=True)),
                ('vacancies', models.DecimalField(decimal_places=0, max_digits=2)),
                ('internship_bachelor', models.CharField(blank=True, choices=[('CTeSP', 'CTeSP'), ('Licenciatura', 'Licenciatura'), ('Mestrado', 'Mestrado'), ('Cursos de Especialização', 'Cursos de Especialização')], max_length=24, null=True)),
                ('internship_courses_ctesp', models.CharField(blank=True, choices=[('Cibersegurança', 'Cibersegurança'), ('Gestão de PME', 'Gestão de PME'), ('Instalações Elétricas e Automação', 'Instalações Elétricas e Automação'), ('Manutenção Industrial', 'Manutenção Industrial'), ('Programação de Sistemas de Informação', 'Programação de Sistemas de Informação'), ('Redes e Sistemas Informáticos', 'Redes e Sistemas Informáticos'), ('Tecnologia Mecânica', 'Tecnologia Mecânica')], max_length=37, null=True)),
                ('internship_courses_licenciatura', models.CharField(blank=True, choices=[('Eletrónica e Mecânica Industrial', 'Eletrónica e Mecânica Industrial'), ('Gestão Comercial', 'Gestão Comercial'), ('Gestão da Qualidade', 'Gestão da Qualidade'), ('Gestão Pública', 'Gestão Pública'), ('Secretariado e Comunicação Empresarial', 'Secretariado e Comunicação Empresarial'), ('Tecnologias da Informação', 'Tecnologias da Informação')], max_length=38, null=True)),
                ('internship_courses_mestrado', models.CharField(blank=True, choices=[('Assessoria de Direção e Comunicação nas Organizações', 'Assessoria de Direção e Comunicação nas Organizações'), ('Gestão Comercial', 'Gestão Comercial'), ('Gestão da Qualidade Total', 'Gestão da Qualidade Total'), ('Gestão e Negócios Digitais', 'Gestão e Negócios Digitais'), ('Informática Aplicada', 'Informática Aplicada')], max_length=52, null=True)),
                ('internship_courses_ce', models.CharField(blank=True, choices=[('Auditorias de Sistemas Integrados de Gestão', 'Auditorias de Sistemas Integrados de Gestão'), ('Dados e Inteligência Artificial', 'Dados e Inteligência Artificial'), ('Desenvolvimento de Aplicações Móveis', 'Desenvolvimento de Aplicações Móveis'), ('Excelência nas Organizações', 'Excelência nas Organizações'), ('Gestão de Negócios de Retalho', 'Gestão de Negócios de Retalho')], max_length=43, null=True)),
                ('total_hours', models.IntegerField(blank=True, null=True)),
                ('programming_lang_python', models.BooleanField(default=False)),
                ('programming_lang_java', models.BooleanField(default=False)),
                ('programming_lang_c_1', models.BooleanField(default=False)),
                ('programming_lang_c_2', models.BooleanField(default=False)),
                ('programming_lang_javascript', models.BooleanField(default=False)),
                ('programming_lang_sql', models.BooleanField(default=False)),
                ('programming_lang_php', models.BooleanField(default=False)),
                ('programming_lang_go', models.BooleanField(default=False)),
                ('programming_lang_kotlin', models.BooleanField(default=False)),
                ('programming_lang_matlab', models.BooleanField(default=False)),
                ('programming_lang_swift', models.BooleanField(default=False)),
                ('programming_lang_rust', models.BooleanField(default=False)),
                ('programming_lang_ruby', models.BooleanField(default=False)),
                ('programming_lang_dart', models.BooleanField(default=False)),
                ('programming_lang_scala', models.BooleanField(default=False)),
                ('programming_fw_frontend_angular', models.BooleanField(default=False)),
                ('programming_fw_frontend_jquery', models.BooleanField(default=False)),
                ('programming_fw_frontend_react', models.BooleanField(default=False)),
                ('programming_fw_frontend_ruby', models.BooleanField(default=False)),
                ('programming_fw_frontend_vuejs', models.BooleanField(default=False)),
                ('programming_fw_backend_aspnet', models.BooleanField(default=False)),
                ('programming_fw_backend_django', models.BooleanField(default=False)),
                ('programming_fw_backend_express', models.BooleanField(default=False)),
                ('programming_fw_backend_laravel', models.BooleanField(default=False)),
                ('programming_fw_backend_nodejs', models.BooleanField(default=False)),
                ('programming_fw_backend_spring', models.BooleanField(default=False)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('picture1', models.ImageField(blank=True, null=True, upload_to='pictures/%Y/%m/%d/')),
                ('picture2', models.ImageField(blank=True, null=True, upload_to='pictures/%Y/%m/%d/')),
                ('picture3', models.ImageField(blank=True, null=True, upload_to='pictures/%Y/%m/%d/')),
                ('picture4', models.ImageField(blank=True, null=True, upload_to='pictures/%Y/%m/%d/')),
                ('picture5', models.ImageField(blank=True, null=True, upload_to='pictures/%Y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='Poi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120, null=True)),
                ('type', models.CharField(choices=[('University', 'University'), ('Hospital', 'Hospital'), ('Stadium', 'Stadium')], max_length=50)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
            ],
        ),
    ]
