# Generated by Django 4.2.1 on 2023-06-13 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='area',
            field=models.CharField(blank=True, choices=[('Aveiro', 'Aveiro'), ('Outros Distritos', 'Outros Distritos')], max_length=20, null=True),
        ),
    ]
